print ('Lets add numbers')
print ('pick a number between one and ten')
myFirstNumber = input ()
print ('ok you picked' + myFirstNumber )
print ('ok pick another number between one and ten' )
mySecondNumber = input ()
print ('ok you picked' + mySecondNumber)
myFirstNumber = int(myFirstNumber)
mySecondNumber = int(mySecondNumber)
combinedNumber = myFirstNumber + mySecondNumber
print ('your combined number is')
print (combinedNumber)